//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Windows.Forms;


namespace NSDummy {
    
    public partial class dummyForm : System.Windows.Forms.Form {
        #region fields
        /// <summary>
        /// Required designer variable.
        /// </summary>
        IContainer components = null;
        MenuStrip ms1;
        ToolStripMenuItem tsmiFile;
        ToolStripMenuItem tsmiFileExit;
        #endregion
        #region Windows Form Designer generated code
        /// <summary>Required method for Designer support</summary>
        void InitializeComponent() {
            this.ms1 = new MenuStrip();
            this.tsmiFile = new ToolStripMenuItem();
            this.tsmiFileExit = new ToolStripMenuItem();
            this.ms1.Items.AddRange(new ToolStripItem[] {
                        this.tsmiFile});
            this.tsmiFile.DropDownItems.AddRange(new ToolStripItem[] {
                        this.tsmiFileExit});
            this.ms1.Name = "ms1";
            this.ms1.Text = "ms1";
            this.tsmiFile.Name = "tsmiFile";
            this.tsmiFile.Text = "File";
            this.tsmiFileExit.Name = "tsmiFileExit";
            this.tsmiFileExit.Text = "Exit";
            this.tsmiFileExit.Click += new System.EventHandler(this.exitClick);
            this.Controls.Add(this.ms1);
            this.MainMenuStrip = this.ms1;
            this.Load += new System.EventHandler(this.formLoad);
        }
        #endregion
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing) {
            if (disposing) {
                if ((components != null)) {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }
    }
}
