//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Windows.Forms;


namespace NSTcp_listener {
    
    public partial class tcp_listenerForm : System.Windows.Forms.Form {
        #region fields
        /// <summary>
        /// Required designer variable.
        /// </summary>
        IContainer components = null;
        MenuStrip ms1;
        ToolStripMenuItem tsmiFile;
        ToolStripMenuItem tsmiFileExit;
        #endregion
        #region Windows Form Designer generated code
        /// <summary>Required method for Designer support</summary>
        void InitializeComponent() {
			this.components = new System.ComponentModel.Container();
			this.ms1 = new System.Windows.Forms.MenuStrip();
			this.tsmiFile = new System.Windows.Forms.ToolStripMenuItem();
			this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.tsmiFileExit = new System.Windows.Forms.ToolStripMenuItem();
			this.btnSendIRData = new System.Windows.Forms.Button();
			this.label1 = new System.Windows.Forms.Label();
			this.label2 = new System.Windows.Forms.Label();
			this.tbIPAddress = new System.Windows.Forms.TextBox();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.tbPort = new System.Windows.Forms.TextBox();
			this.ep1 = new System.Windows.Forms.ErrorProvider(this.components);
			this.gbSerialNumber = new System.Windows.Forms.GroupBox();
			this.tbSerialNumber = new System.Windows.Forms.TextBox();
			this.btnStart = new System.Windows.Forms.Button();
			this.btnStop = new System.Windows.Forms.Button();
			this.btnUseSN = new System.Windows.Forms.Button();
			this.ms1.SuspendLayout();
			this.groupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.ep1)).BeginInit();
			this.gbSerialNumber.SuspendLayout();
			this.SuspendLayout();
			// 
			// ms1
			// 
			this.ms1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsmiFile});
			this.ms1.Location = new System.Drawing.Point(0, 0);
			this.ms1.Name = "ms1";
			this.ms1.Size = new System.Drawing.Size(284, 24);
			this.ms1.TabIndex = 0;
			this.ms1.Text = "ms1";
			// 
			// tsmiFile
			// 
			this.tsmiFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripSeparator1,
            this.tsmiFileExit});
			this.tsmiFile.Name = "tsmiFile";
			this.tsmiFile.Size = new System.Drawing.Size(37, 20);
			this.tsmiFile.Text = "File";
			// 
			// toolStripSeparator1
			// 
			this.toolStripSeparator1.Name = "toolStripSeparator1";
			this.toolStripSeparator1.Size = new System.Drawing.Size(89, 6);
			// 
			// tsmiFileExit
			// 
			this.tsmiFileExit.Name = "tsmiFileExit";
			this.tsmiFileExit.Size = new System.Drawing.Size(92, 22);
			this.tsmiFileExit.Text = "Exit";
			this.tsmiFileExit.Click += new System.EventHandler(this.exitClick);
			// 
			// btnSendIRData
			// 
			this.btnSendIRData.Location = new System.Drawing.Point(183, 131);
			this.btnSendIRData.Name = "btnSendIRData";
			this.btnSendIRData.Size = new System.Drawing.Size(75, 23);
			this.btnSendIRData.TabIndex = 1;
			this.btnSendIRData.Text = "Send IR Data";
			this.btnSendIRData.UseVisualStyleBackColor = true;
			this.btnSendIRData.Click += new System.EventHandler(this.requestSendIRData);
			// 
			// label1
			// 
			this.label1.AutoSize = true;
			this.label1.Location = new System.Drawing.Point(20, 26);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(61, 13);
			this.label1.TabIndex = 2;
			this.label1.Text = "IP Address:";
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Location = new System.Drawing.Point(20, 48);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(39, 13);
			this.label2.TabIndex = 3;
			this.label2.Text = "Port #:";
			// 
			// tbIPAddress
			// 
			this.tbIPAddress.Location = new System.Drawing.Point(78, 19);
			this.tbIPAddress.Name = "tbIPAddress";
			this.tbIPAddress.Size = new System.Drawing.Size(100, 20);
			this.tbIPAddress.TabIndex = 5;
			this.tbIPAddress.Validating += new System.ComponentModel.CancelEventHandler(this.tbIPAddress_Validating);
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this.tbPort);
			this.groupBox1.Controls.Add(this.tbIPAddress);
			this.groupBox1.Controls.Add(this.label1);
			this.groupBox1.Controls.Add(this.label2);
			this.groupBox1.Location = new System.Drawing.Point(27, 46);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(231, 79);
			this.groupBox1.TabIndex = 8;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Configuration";
			// 
			// tbPort
			// 
			this.tbPort.Location = new System.Drawing.Point(78, 45);
			this.tbPort.Name = "tbPort";
			this.tbPort.Size = new System.Drawing.Size(100, 20);
			this.tbPort.TabIndex = 10;
			this.tbPort.Validating += new System.ComponentModel.CancelEventHandler(this.tbPort_Validating);
			// 
			// ep1
			// 
			this.ep1.ContainerControl = this;
			// 
			// gbSerialNumber
			// 
			this.gbSerialNumber.Controls.Add(this.btnUseSN);
			this.gbSerialNumber.Controls.Add(this.tbSerialNumber);
			this.gbSerialNumber.Location = new System.Drawing.Point(27, 160);
			this.gbSerialNumber.Name = "gbSerialNumber";
			this.gbSerialNumber.Size = new System.Drawing.Size(231, 69);
			this.gbSerialNumber.TabIndex = 9;
			this.gbSerialNumber.TabStop = false;
			this.gbSerialNumber.Text = "Serial number";
			// 
			// tbSerialNumber
			// 
			this.tbSerialNumber.Location = new System.Drawing.Point(6, 19);
			this.tbSerialNumber.Name = "tbSerialNumber";
			this.tbSerialNumber.Size = new System.Drawing.Size(219, 20);
			this.tbSerialNumber.TabIndex = 7;
			this.tbSerialNumber.Validating += new System.ComponentModel.CancelEventHandler(this.tbSerialNumber_Validating);
			// 
			// btnStart
			// 
			this.btnStart.Location = new System.Drawing.Point(28, 131);
			this.btnStart.Name = "btnStart";
			this.btnStart.Size = new System.Drawing.Size(75, 23);
			this.btnStart.TabIndex = 10;
			this.btnStart.Text = "Start";
			this.btnStart.UseVisualStyleBackColor = true;
			this.btnStart.Click += new System.EventHandler(this.btnStart_Click);
			// 
			// btnStop
			// 
			this.btnStop.Location = new System.Drawing.Point(105, 131);
			this.btnStop.Name = "btnStop";
			this.btnStop.Size = new System.Drawing.Size(75, 23);
			this.btnStop.TabIndex = 11;
			this.btnStop.Text = "Stop";
			this.btnStop.UseVisualStyleBackColor = true;
			this.btnStop.Click += new System.EventHandler(this.btnStop_Click);
			// 
			// btnUseSN
			// 
			this.btnUseSN.Location = new System.Drawing.Point(78, 40);
			this.btnUseSN.Name = "btnUseSN";
			this.btnUseSN.Size = new System.Drawing.Size(75, 23);
			this.btnUseSN.TabIndex = 12;
			this.btnUseSN.Text = "Use S/N";
			this.btnUseSN.UseVisualStyleBackColor = true;
			this.btnUseSN.Click += new System.EventHandler(this.btnUseSN_Click);
			// 
			// tcp_listenerForm
			// 
			this.CausesValidation = false;
			this.ClientSize = new System.Drawing.Size(284, 264);
			this.Controls.Add(this.btnStop);
			this.Controls.Add(this.btnStart);
			this.Controls.Add(this.gbSerialNumber);
			this.Controls.Add(this.btnSendIRData);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this.ms1);
			this.MainMenuStrip = this.ms1;
			this.Name = "tcp_listenerForm";
			this.Load += new System.EventHandler(this.formLoad);
			this.LocationChanged += new System.EventHandler(this.tcp_listenerForm_LocationChanged);
			this.SizeChanged += new System.EventHandler(this.tcp_listenerForm_SizeChanged);
			this.ms1.ResumeLayout(false);
			this.ms1.PerformLayout();
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.ep1)).EndInit();
			this.gbSerialNumber.ResumeLayout(false);
			this.gbSerialNumber.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();

        }
        #endregion
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing) {
            if (disposing) {
                if ((components != null)) {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }
         ToolStripSeparator toolStripSeparator1;
		private Button btnSendIRData;
		private Label label1;
		private Label label2;
		private TextBox tbIPAddress;
		private GroupBox groupBox1;
		private TextBox tbPort;
		private ErrorProvider ep1;
		private GroupBox gbSerialNumber;
		private TextBox tbSerialNumber;
		private Button btnStop;
		private Button btnStart;
		private Button btnUseSN;
	}
}
