//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tests {
    
    public class Tester {
        public void runTests() {
            new TestMid0001().runTests();
            new TestMid0002().runTests();
            new TestMid0003().runTests();
            new TestMid0004().runTests();
            new TestMid0005().runTests();
            new TestMid0006().runTests();
            new TestMid0008().runTests();
            new TestMid0010().runTests();
            new TestMid0011().runTests();
            new TestMid0012().runTests();
            new TestMid0013().runTests();
            new TestMid0014().runTests();
            new TestMid0015().runTests();
            new TestMid0016().runTests();
            new TestMid0017().runTests();
            new TestMid0018().runTests();
            new TestMid0019().runTests();
            new TestMid0020().runTests();
            new TestMid0021().runTests();
            new TestMid0022().runTests();
            new TestMid0023().runTests();
            new TestMid0024().runTests();
            new TestMid0030().runTests();
            new TestMid0031().runTests();
            new TestMid0032().runTests();
            new TestMid0033().runTests();
            new TestMid0034().runTests();
            new TestMid0035().runTests();
            new TestMid0036().runTests();
            new TestMid0037().runTests();
            new TestMid0038().runTests();
            new TestMid0039().runTests();
            new TestMid0040().runTests();
            new TestMid0041().runTests();
            new TestMid0042().runTests();
            new TestMid0043().runTests();
            new TestMid0044().runTests();
            new TestMid0045().runTests();
            new TestMid0046().runTests();
            new TestMid0047().runTests();
            new TestMid0048().runTests();
            new TestMid0050().runTests();
            new TestMid0051().runTests();
            new TestMid0052().runTests();
            new TestMid0053().runTests();
            new TestMid0054().runTests();
            new TestMid0060().runTests();
            new TestMid0061().runTests();
            new TestMid0062().runTests();
            new TestMid0063().runTests();
            new TestMid0064().runTests();
            new TestMid0065().runTests();
            new TestMid0070().runTests();
            new TestMid0071().runTests();
            new TestMid0072().runTests();
            new TestMid0073().runTests();
            new TestMid0074().runTests();
            new TestMid0075().runTests();
            new TestMid0076().runTests();
            new TestMid0077().runTests();
            new TestMid0078().runTests();
            new TestMid0080().runTests();
            new TestMid0081().runTests();
            new TestMid0082().runTests();
            new TestMid0090().runTests();
            new TestMid0091().runTests();
            new TestMid0092().runTests();
            new TestMid0093().runTests();
            new TestMid0105().runTests();
            new TestMid0106().runTests();
            new TestMid0107().runTests();
            new TestMid0108().runTests();
            new TestMid0109().runTests();
            new TestMid0110().runTests();
            new TestMid0111().runTests();
            new TestMid0113().runTests();
            new TestMid0120().runTests();
            new TestMid0121().runTests();
            new TestMid0122().runTests();
            new TestMid0123().runTests();
            new TestMid0124().runTests();
            new TestMid0125().runTests();
            new TestMid0126().runTests();
            new TestMid0127().runTests();
            new TestMid0128().runTests();
            new TestMid0129().runTests();
            new TestMid0130().runTests();
            new TestMid0131().runTests();
            new TestMid0132().runTests();
            new TestMid0133().runTests();
            new TestMid0140().runTests();
            new TestMid0150().runTests();
            new TestMid0151().runTests();
            new TestMid0152().runTests();
            new TestMid0153().runTests();
            new TestMid0154().runTests();
            new TestMid0155().runTests();
            new TestMid0156().runTests();
            new TestMid0157().runTests();
            new TestMid0200().runTests();
            new TestMid0210().runTests();
            new TestMid0211().runTests();
            new TestMid0212().runTests();
            new TestMid0213().runTests();
            new TestMid0214().runTests();
            new TestMid0215().runTests();
            new TestMid0216().runTests();
            new TestMid0217().runTests();
            new TestMid0218().runTests();
            new TestMid0219().runTests();
            new TestMid0220().runTests();
            new TestMid0221().runTests();
            new TestMid0222().runTests();
            new TestMid0223().runTests();
            new TestMid0224().runTests();
            new TestMid0225().runTests();
            new TestMid0240().runTests();
            new TestMid0241().runTests();
            new TestMid0242().runTests();
            new TestMid0243().runTests();
            new TestMid0244().runTests();
            new TestMid0245().runTests();
            new TestMid0250().runTests();
            new TestMid0251().runTests();
            new TestMid0252().runTests();
            new TestMid0253().runTests();
            new TestMid0254().runTests();
            new TestMid0255().runTests();
            new TestMid0260().runTests();
            new TestMid0261().runTests();
            new TestMid0262().runTests();
            new TestMid0263().runTests();
            new TestMid0264().runTests();
            new TestMid0265().runTests();
            new TestMid0270().runTests();
            new TestMid0300().runTests();
            new TestMid0301().runTests();
            new TestMid0400().runTests();
            new TestMid0401().runTests();
            new TestMid0402().runTests();
            new TestMid0403().runTests();
            new TestMid0410().runTests();
            new TestMid0411().runTests();
            new TestMid0420().runTests();
            new TestMid0421().runTests();
            new TestMid0422().runTests();
            new TestMid0423().runTests();
            new TestMid0500().runTests();
            new TestMid0501().runTests();
            new TestMid0502().runTests();
            new TestMid0503().runTests();
            new TestMid0504().runTests();
            new TestMid1201().runTests();
            new TestMid1202().runTests();
            new TestMid1203().runTests();
            new TestMid2504().runTests();
            new TestMid9999().runTests();
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Communication.Mid0001</para></remarks>
    public class TestMid0001 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Communication.Mid0001 mid = new OpenProtocolInterpreter.Communication.Mid0001(0, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Communication.Mid0001 mid = new OpenProtocolInterpreter.Communication.Mid0001(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Communication.Mid0001 mid = new OpenProtocolInterpreter.Communication.Mid0001(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Communication.Mid0001 mid = new OpenProtocolInterpreter.Communication.Mid0001(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Communication.Mid0001 mid = new OpenProtocolInterpreter.Communication.Mid0001(-1, 5);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Communication.Mid0002</para></remarks>
    public class TestMid0002 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
            testRevision6();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Communication.Mid0002 mid = new OpenProtocolInterpreter.Communication.Mid0002(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Communication.Mid0002 mid = new OpenProtocolInterpreter.Communication.Mid0002(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Communication.Mid0002 mid = new OpenProtocolInterpreter.Communication.Mid0002(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Communication.Mid0002 mid = new OpenProtocolInterpreter.Communication.Mid0002(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Communication.Mid0002 mid = new OpenProtocolInterpreter.Communication.Mid0002(-1, 5);
        }
        void testRevision6() {
            OpenProtocolInterpreter.Communication.Mid0002 mid = new OpenProtocolInterpreter.Communication.Mid0002(-1, 6);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Communication.Mid0003</para></remarks>
    public class TestMid0003 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Communication.Mid0003 mid = new OpenProtocolInterpreter.Communication.Mid0003(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Communication.Mid0004</para></remarks>
    public class TestMid0004 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Communication.Mid0004 mid = new OpenProtocolInterpreter.Communication.Mid0004(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Communication.Mid0005</para></remarks>
    public class TestMid0005 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Communication.Mid0005 mid = new OpenProtocolInterpreter.Communication.Mid0005(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Communication.Mid0006</para></remarks>
    public class TestMid0006 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Communication.Mid0006 mid = new OpenProtocolInterpreter.Communication.Mid0006(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Communication.Mid0008</para></remarks>
    public class TestMid0008 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Communication.Mid0008 mid = new OpenProtocolInterpreter.Communication.Mid0008(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0010</para></remarks>
    public class TestMid0010 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0010 mid = new OpenProtocolInterpreter.ParameterSet.Mid0010(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.ParameterSet.Mid0010 mid = new OpenProtocolInterpreter.ParameterSet.Mid0010(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.ParameterSet.Mid0010 mid = new OpenProtocolInterpreter.ParameterSet.Mid0010(-1, 3);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0011</para></remarks>
    public class TestMid0011 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0011 mid = new OpenProtocolInterpreter.ParameterSet.Mid0011(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0012</para></remarks>
    public class TestMid0012 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0012 mid = new OpenProtocolInterpreter.ParameterSet.Mid0012(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.ParameterSet.Mid0012 mid = new OpenProtocolInterpreter.ParameterSet.Mid0012(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.ParameterSet.Mid0012 mid = new OpenProtocolInterpreter.ParameterSet.Mid0012(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.ParameterSet.Mid0012 mid = new OpenProtocolInterpreter.ParameterSet.Mid0012(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0013</para></remarks>
    public class TestMid0013 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0013 mid = new OpenProtocolInterpreter.ParameterSet.Mid0013(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.ParameterSet.Mid0013 mid = new OpenProtocolInterpreter.ParameterSet.Mid0013(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0014</para></remarks>
    public class TestMid0014 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0014 mid = new OpenProtocolInterpreter.ParameterSet.Mid0014(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0015</para></remarks>
    public class TestMid0015 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0015 mid = new OpenProtocolInterpreter.ParameterSet.Mid0015(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.ParameterSet.Mid0015 mid = new OpenProtocolInterpreter.ParameterSet.Mid0015(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0016</para></remarks>
    public class TestMid0016 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0016 mid = new OpenProtocolInterpreter.ParameterSet.Mid0016(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0017</para></remarks>
    public class TestMid0017 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0017 mid = new OpenProtocolInterpreter.ParameterSet.Mid0017(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0018</para></remarks>
    public class TestMid0018 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0018 mid = new OpenProtocolInterpreter.ParameterSet.Mid0018(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0019</para></remarks>
    public class TestMid0019 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0019 mid = new OpenProtocolInterpreter.ParameterSet.Mid0019(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0020</para></remarks>
    public class TestMid0020 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0020 mid = new OpenProtocolInterpreter.ParameterSet.Mid0020(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0021</para></remarks>
    public class TestMid0021 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0021 mid = new OpenProtocolInterpreter.ParameterSet.Mid0021(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0022</para></remarks>
    public class TestMid0022 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0022 mid = new OpenProtocolInterpreter.ParameterSet.Mid0022(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0023</para></remarks>
    public class TestMid0023 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0023 mid = new OpenProtocolInterpreter.ParameterSet.Mid0023(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid0024</para></remarks>
    public class TestMid0024 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid0024 mid = new OpenProtocolInterpreter.ParameterSet.Mid0024(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0030</para></remarks>
    public class TestMid0030 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0030 mid = new OpenProtocolInterpreter.Job.Mid0030(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0030 mid = new OpenProtocolInterpreter.Job.Mid0030(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0031</para></remarks>
    public class TestMid0031 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0031 mid = new OpenProtocolInterpreter.Job.Mid0031(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0032</para></remarks>
    public class TestMid0032 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0032 mid = new OpenProtocolInterpreter.Job.Mid0032(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0032 mid = new OpenProtocolInterpreter.Job.Mid0032(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Job.Mid0032 mid = new OpenProtocolInterpreter.Job.Mid0032(-1, 3);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0033</para></remarks>
    public class TestMid0033 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0033 mid = new OpenProtocolInterpreter.Job.Mid0033(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0033 mid = new OpenProtocolInterpreter.Job.Mid0033(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Job.Mid0033 mid = new OpenProtocolInterpreter.Job.Mid0033(-1, 3);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0034</para></remarks>
    public class TestMid0034 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0034 mid = new OpenProtocolInterpreter.Job.Mid0034(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0034 mid = new OpenProtocolInterpreter.Job.Mid0034(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Job.Mid0034 mid = new OpenProtocolInterpreter.Job.Mid0034(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Job.Mid0034 mid = new OpenProtocolInterpreter.Job.Mid0034(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0035</para></remarks>
    public class TestMid0035 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0035 mid = new OpenProtocolInterpreter.Job.Mid0035(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0035 mid = new OpenProtocolInterpreter.Job.Mid0035(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Job.Mid0035 mid = new OpenProtocolInterpreter.Job.Mid0035(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Job.Mid0035 mid = new OpenProtocolInterpreter.Job.Mid0035(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0036</para></remarks>
    public class TestMid0036 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0036 mid = new OpenProtocolInterpreter.Job.Mid0036(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0036 mid = new OpenProtocolInterpreter.Job.Mid0036(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Job.Mid0036 mid = new OpenProtocolInterpreter.Job.Mid0036(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Job.Mid0036 mid = new OpenProtocolInterpreter.Job.Mid0036(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0037</para></remarks>
    public class TestMid0037 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0037 mid = new OpenProtocolInterpreter.Job.Mid0037(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0037 mid = new OpenProtocolInterpreter.Job.Mid0037(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Job.Mid0037 mid = new OpenProtocolInterpreter.Job.Mid0037(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Job.Mid0037 mid = new OpenProtocolInterpreter.Job.Mid0037(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0038</para></remarks>
    public class TestMid0038 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0038 mid = new OpenProtocolInterpreter.Job.Mid0038(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0038 mid = new OpenProtocolInterpreter.Job.Mid0038(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Mid0039</para></remarks>
    public class TestMid0039 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Mid0039 mid = new OpenProtocolInterpreter.Job.Mid0039(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Mid0039 mid = new OpenProtocolInterpreter.Job.Mid0039(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0040</para></remarks>
    public class TestMid0040 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0040 mid = new OpenProtocolInterpreter.Tool.Mid0040(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Tool.Mid0040 mid = new OpenProtocolInterpreter.Tool.Mid0040(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Tool.Mid0040 mid = new OpenProtocolInterpreter.Tool.Mid0040(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Tool.Mid0040 mid = new OpenProtocolInterpreter.Tool.Mid0040(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Tool.Mid0040 mid = new OpenProtocolInterpreter.Tool.Mid0040(-1, 5);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0041</para></remarks>
    public class TestMid0041 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0041 mid = new OpenProtocolInterpreter.Tool.Mid0041(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Tool.Mid0041 mid = new OpenProtocolInterpreter.Tool.Mid0041(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Tool.Mid0041 mid = new OpenProtocolInterpreter.Tool.Mid0041(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Tool.Mid0041 mid = new OpenProtocolInterpreter.Tool.Mid0041(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Tool.Mid0041 mid = new OpenProtocolInterpreter.Tool.Mid0041(-1, 5);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0042</para></remarks>
    public class TestMid0042 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0042 mid = new OpenProtocolInterpreter.Tool.Mid0042(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0043</para></remarks>
    public class TestMid0043 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0043 mid = new OpenProtocolInterpreter.Tool.Mid0043(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0044</para></remarks>
    public class TestMid0044 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0044 mid = new OpenProtocolInterpreter.Tool.Mid0044(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0045</para></remarks>
    public class TestMid0045 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0045 mid = new OpenProtocolInterpreter.Tool.Mid0045(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0046</para></remarks>
    public class TestMid0046 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0046 mid = new OpenProtocolInterpreter.Tool.Mid0046(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0047</para></remarks>
    public class TestMid0047 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0047 mid = new OpenProtocolInterpreter.Tool.Mid0047(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tool.Mid0048</para></remarks>
    public class TestMid0048 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tool.Mid0048 mid = new OpenProtocolInterpreter.Tool.Mid0048(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Vin.Mid0050</para></remarks>
    public class TestMid0050 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Vin.Mid0050 mid = new OpenProtocolInterpreter.Vin.Mid0050(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Vin.Mid0051</para></remarks>
    public class TestMid0051 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Vin.Mid0051 mid = new OpenProtocolInterpreter.Vin.Mid0051(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Vin.Mid0051 mid = new OpenProtocolInterpreter.Vin.Mid0051(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Vin.Mid0052</para></remarks>
    public class TestMid0052 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Vin.Mid0052 mid = new OpenProtocolInterpreter.Vin.Mid0052(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Vin.Mid0052 mid = new OpenProtocolInterpreter.Vin.Mid0052(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Vin.Mid0053</para></remarks>
    public class TestMid0053 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Vin.Mid0053 mid = new OpenProtocolInterpreter.Vin.Mid0053(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Vin.Mid0053 mid = new OpenProtocolInterpreter.Vin.Mid0053(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Vin.Mid0054</para></remarks>
    public class TestMid0054 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Vin.Mid0054 mid = new OpenProtocolInterpreter.Vin.Mid0054(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tightening.Mid0060</para></remarks>
    public class TestMid0060 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
            testRevision6();
            testRevision7();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tightening.Mid0060 mid = new OpenProtocolInterpreter.Tightening.Mid0060(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Tightening.Mid0060 mid = new OpenProtocolInterpreter.Tightening.Mid0060(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Tightening.Mid0060 mid = new OpenProtocolInterpreter.Tightening.Mid0060(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Tightening.Mid0060 mid = new OpenProtocolInterpreter.Tightening.Mid0060(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Tightening.Mid0060 mid = new OpenProtocolInterpreter.Tightening.Mid0060(-1, 5);
        }
        void testRevision6() {
            OpenProtocolInterpreter.Tightening.Mid0060 mid = new OpenProtocolInterpreter.Tightening.Mid0060(-1, 6);
        }
        void testRevision7() {
            OpenProtocolInterpreter.Tightening.Mid0060 mid = new OpenProtocolInterpreter.Tightening.Mid0060(-1, 7);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tightening.Mid0061</para></remarks>
    public class TestMid0061 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
            testRevision6();
            testRevision7();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tightening.Mid0061 mid = new OpenProtocolInterpreter.Tightening.Mid0061(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Tightening.Mid0061 mid = new OpenProtocolInterpreter.Tightening.Mid0061(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Tightening.Mid0061 mid = new OpenProtocolInterpreter.Tightening.Mid0061(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Tightening.Mid0061 mid = new OpenProtocolInterpreter.Tightening.Mid0061(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Tightening.Mid0061 mid = new OpenProtocolInterpreter.Tightening.Mid0061(-1, 5);
        }
        void testRevision6() {
            OpenProtocolInterpreter.Tightening.Mid0061 mid = new OpenProtocolInterpreter.Tightening.Mid0061(-1, 6);
        }
        void testRevision7() {
            OpenProtocolInterpreter.Tightening.Mid0061 mid = new OpenProtocolInterpreter.Tightening.Mid0061(-1, 7);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tightening.Mid0062</para></remarks>
    public class TestMid0062 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
            testRevision6();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tightening.Mid0062 mid = new OpenProtocolInterpreter.Tightening.Mid0062(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Tightening.Mid0062 mid = new OpenProtocolInterpreter.Tightening.Mid0062(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Tightening.Mid0062 mid = new OpenProtocolInterpreter.Tightening.Mid0062(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Tightening.Mid0062 mid = new OpenProtocolInterpreter.Tightening.Mid0062(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Tightening.Mid0062 mid = new OpenProtocolInterpreter.Tightening.Mid0062(-1, 5);
        }
        void testRevision6() {
            OpenProtocolInterpreter.Tightening.Mid0062 mid = new OpenProtocolInterpreter.Tightening.Mid0062(-1, 6);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tightening.Mid0063</para></remarks>
    public class TestMid0063 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
            testRevision6();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tightening.Mid0063 mid = new OpenProtocolInterpreter.Tightening.Mid0063(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Tightening.Mid0063 mid = new OpenProtocolInterpreter.Tightening.Mid0063(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Tightening.Mid0063 mid = new OpenProtocolInterpreter.Tightening.Mid0063(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Tightening.Mid0063 mid = new OpenProtocolInterpreter.Tightening.Mid0063(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Tightening.Mid0063 mid = new OpenProtocolInterpreter.Tightening.Mid0063(-1, 5);
        }
        void testRevision6() {
            OpenProtocolInterpreter.Tightening.Mid0063 mid = new OpenProtocolInterpreter.Tightening.Mid0063(-1, 6);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tightening.Mid0064</para></remarks>
    public class TestMid0064 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
            testRevision6();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tightening.Mid0064 mid = new OpenProtocolInterpreter.Tightening.Mid0064(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Tightening.Mid0064 mid = new OpenProtocolInterpreter.Tightening.Mid0064(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Tightening.Mid0064 mid = new OpenProtocolInterpreter.Tightening.Mid0064(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Tightening.Mid0064 mid = new OpenProtocolInterpreter.Tightening.Mid0064(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Tightening.Mid0064 mid = new OpenProtocolInterpreter.Tightening.Mid0064(-1, 5);
        }
        void testRevision6() {
            OpenProtocolInterpreter.Tightening.Mid0064 mid = new OpenProtocolInterpreter.Tightening.Mid0064(-1, 6);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Tightening.Mid0065</para></remarks>
    public class TestMid0065 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
            testRevision5();
            testRevision6();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Tightening.Mid0065 mid = new OpenProtocolInterpreter.Tightening.Mid0065(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Tightening.Mid0065 mid = new OpenProtocolInterpreter.Tightening.Mid0065(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.Tightening.Mid0065 mid = new OpenProtocolInterpreter.Tightening.Mid0065(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.Tightening.Mid0065 mid = new OpenProtocolInterpreter.Tightening.Mid0065(-1, 4);
        }
        void testRevision5() {
            OpenProtocolInterpreter.Tightening.Mid0065 mid = new OpenProtocolInterpreter.Tightening.Mid0065(-1, 5);
        }
        void testRevision6() {
            OpenProtocolInterpreter.Tightening.Mid0065 mid = new OpenProtocolInterpreter.Tightening.Mid0065(-1, 6);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0070</para></remarks>
    public class TestMid0070 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0070 mid = new OpenProtocolInterpreter.Alarm.Mid0070(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Alarm.Mid0070 mid = new OpenProtocolInterpreter.Alarm.Mid0070(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0071</para></remarks>
    public class TestMid0071 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0071 mid = new OpenProtocolInterpreter.Alarm.Mid0071(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Alarm.Mid0071 mid = new OpenProtocolInterpreter.Alarm.Mid0071(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0072</para></remarks>
    public class TestMid0072 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0072 mid = new OpenProtocolInterpreter.Alarm.Mid0072(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Alarm.Mid0072 mid = new OpenProtocolInterpreter.Alarm.Mid0072(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0073</para></remarks>
    public class TestMid0073 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0073 mid = new OpenProtocolInterpreter.Alarm.Mid0073(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Alarm.Mid0073 mid = new OpenProtocolInterpreter.Alarm.Mid0073(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0074</para></remarks>
    public class TestMid0074 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0074 mid = new OpenProtocolInterpreter.Alarm.Mid0074(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Alarm.Mid0074 mid = new OpenProtocolInterpreter.Alarm.Mid0074(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0075</para></remarks>
    public class TestMid0075 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0075 mid = new OpenProtocolInterpreter.Alarm.Mid0075(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Alarm.Mid0075 mid = new OpenProtocolInterpreter.Alarm.Mid0075(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0076</para></remarks>
    public class TestMid0076 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0076 mid = new OpenProtocolInterpreter.Alarm.Mid0076(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0077</para></remarks>
    public class TestMid0077 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0077 mid = new OpenProtocolInterpreter.Alarm.Mid0077(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Alarm.Mid0078</para></remarks>
    public class TestMid0078 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Alarm.Mid0078 mid = new OpenProtocolInterpreter.Alarm.Mid0078(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Time.Mid0080</para></remarks>
    public class TestMid0080 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Time.Mid0080 mid = new OpenProtocolInterpreter.Time.Mid0080(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Time.Mid0081</para></remarks>
    public class TestMid0081 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Time.Mid0081 mid = new OpenProtocolInterpreter.Time.Mid0081(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Time.Mid0082</para></remarks>
    public class TestMid0082 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Time.Mid0082 mid = new OpenProtocolInterpreter.Time.Mid0082(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultiSpindle.Mid0090</para></remarks>
    public class TestMid0090 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultiSpindle.Mid0090 mid = new OpenProtocolInterpreter.MultiSpindle.Mid0090(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultiSpindle.Mid0091</para></remarks>
    public class TestMid0091 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultiSpindle.Mid0091 mid = new OpenProtocolInterpreter.MultiSpindle.Mid0091(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultiSpindle.Mid0092</para></remarks>
    public class TestMid0092 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultiSpindle.Mid0092 mid = new OpenProtocolInterpreter.MultiSpindle.Mid0092(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultiSpindle.Mid0093</para></remarks>
    public class TestMid0093 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultiSpindle.Mid0093 mid = new OpenProtocolInterpreter.MultiSpindle.Mid0093(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PowerMACS.Mid0105</para></remarks>
    public class TestMid0105 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PowerMACS.Mid0105 mid = new OpenProtocolInterpreter.PowerMACS.Mid0105(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.PowerMACS.Mid0105 mid = new OpenProtocolInterpreter.PowerMACS.Mid0105(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.PowerMACS.Mid0105 mid = new OpenProtocolInterpreter.PowerMACS.Mid0105(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.PowerMACS.Mid0105 mid = new OpenProtocolInterpreter.PowerMACS.Mid0105(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PowerMACS.Mid0106</para></remarks>
    public class TestMid0106 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PowerMACS.Mid0106 mid = new OpenProtocolInterpreter.PowerMACS.Mid0106(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.PowerMACS.Mid0106 mid = new OpenProtocolInterpreter.PowerMACS.Mid0106(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.PowerMACS.Mid0106 mid = new OpenProtocolInterpreter.PowerMACS.Mid0106(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.PowerMACS.Mid0106 mid = new OpenProtocolInterpreter.PowerMACS.Mid0106(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PowerMACS.Mid0107</para></remarks>
    public class TestMid0107 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PowerMACS.Mid0107 mid = new OpenProtocolInterpreter.PowerMACS.Mid0107(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.PowerMACS.Mid0107 mid = new OpenProtocolInterpreter.PowerMACS.Mid0107(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.PowerMACS.Mid0107 mid = new OpenProtocolInterpreter.PowerMACS.Mid0107(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.PowerMACS.Mid0107 mid = new OpenProtocolInterpreter.PowerMACS.Mid0107(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PowerMACS.Mid0108</para></remarks>
    public class TestMid0108 {
        public void runTests() {
            testRevision1();
            testRevision2();
            testRevision3();
            testRevision4();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PowerMACS.Mid0108 mid = new OpenProtocolInterpreter.PowerMACS.Mid0108(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.PowerMACS.Mid0108 mid = new OpenProtocolInterpreter.PowerMACS.Mid0108(-1, 2);
        }
        void testRevision3() {
            OpenProtocolInterpreter.PowerMACS.Mid0108 mid = new OpenProtocolInterpreter.PowerMACS.Mid0108(-1, 3);
        }
        void testRevision4() {
            OpenProtocolInterpreter.PowerMACS.Mid0108 mid = new OpenProtocolInterpreter.PowerMACS.Mid0108(-1, 4);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PowerMACS.Mid0109</para></remarks>
    public class TestMid0109 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PowerMACS.Mid0109 mid = new OpenProtocolInterpreter.PowerMACS.Mid0109(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.UserInterface.Mid0110</para></remarks>
    public class TestMid0110 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.UserInterface.Mid0110 mid = new OpenProtocolInterpreter.UserInterface.Mid0110(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.UserInterface.Mid0111</para></remarks>
    public class TestMid0111 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.UserInterface.Mid0111 mid = new OpenProtocolInterpreter.UserInterface.Mid0111(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.UserInterface.Mid0113</para></remarks>
    public class TestMid0113 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.UserInterface.Mid0113 mid = new OpenProtocolInterpreter.UserInterface.Mid0113(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0120</para></remarks>
    public class TestMid0120 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0120 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0120(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0121</para></remarks>
    public class TestMid0121 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0121 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0121(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0122</para></remarks>
    public class TestMid0122 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0122 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0122(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0123</para></remarks>
    public class TestMid0123 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0123 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0123(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0124</para></remarks>
    public class TestMid0124 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0124 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0124(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0125</para></remarks>
    public class TestMid0125 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0125 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0125(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0126</para></remarks>
    public class TestMid0126 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0126 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0126(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0127</para></remarks>
    public class TestMid0127 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0127 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0127(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0128</para></remarks>
    public class TestMid0128 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0128 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0128(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0129</para></remarks>
    public class TestMid0129 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0129 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0129(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.Job.Advanced.Mid0129 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0129(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0130</para></remarks>
    public class TestMid0130 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0130 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0130(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0131</para></remarks>
    public class TestMid0131 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0131 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0131(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0132</para></remarks>
    public class TestMid0132 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0132 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0132(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0133</para></remarks>
    public class TestMid0133 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0133 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0133(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Job.Advanced.Mid0140</para></remarks>
    public class TestMid0140 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Job.Advanced.Mid0140 mid = new OpenProtocolInterpreter.Job.Advanced.Mid0140(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultipleIdentifiers.Mid0150</para></remarks>
    public class TestMid0150 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultipleIdentifiers.Mid0150 mid = new OpenProtocolInterpreter.MultipleIdentifiers.Mid0150(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultipleIdentifiers.Mid0151</para></remarks>
    public class TestMid0151 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultipleIdentifiers.Mid0151 mid = new OpenProtocolInterpreter.MultipleIdentifiers.Mid0151(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultipleIdentifiers.Mid0152</para></remarks>
    public class TestMid0152 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultipleIdentifiers.Mid0152 mid = new OpenProtocolInterpreter.MultipleIdentifiers.Mid0152(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultipleIdentifiers.Mid0153</para></remarks>
    public class TestMid0153 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultipleIdentifiers.Mid0153 mid = new OpenProtocolInterpreter.MultipleIdentifiers.Mid0153(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultipleIdentifiers.Mid0154</para></remarks>
    public class TestMid0154 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultipleIdentifiers.Mid0154 mid = new OpenProtocolInterpreter.MultipleIdentifiers.Mid0154(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultipleIdentifiers.Mid0155</para></remarks>
    public class TestMid0155 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultipleIdentifiers.Mid0155 mid = new OpenProtocolInterpreter.MultipleIdentifiers.Mid0155(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultipleIdentifiers.Mid0156</para></remarks>
    public class TestMid0156 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultipleIdentifiers.Mid0156 mid = new OpenProtocolInterpreter.MultipleIdentifiers.Mid0156(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MultipleIdentifiers.Mid0157</para></remarks>
    public class TestMid0157 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MultipleIdentifiers.Mid0157 mid = new OpenProtocolInterpreter.MultipleIdentifiers.Mid0157(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0200</para></remarks>
    public class TestMid0200 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0200 mid = new OpenProtocolInterpreter.IOInterface.Mid0200(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0210</para></remarks>
    public class TestMid0210 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0210 mid = new OpenProtocolInterpreter.IOInterface.Mid0210(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0211</para></remarks>
    public class TestMid0211 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0211 mid = new OpenProtocolInterpreter.IOInterface.Mid0211(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0212</para></remarks>
    public class TestMid0212 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0212 mid = new OpenProtocolInterpreter.IOInterface.Mid0212(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0213</para></remarks>
    public class TestMid0213 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0213 mid = new OpenProtocolInterpreter.IOInterface.Mid0213(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0214</para></remarks>
    public class TestMid0214 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0214 mid = new OpenProtocolInterpreter.IOInterface.Mid0214(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.IOInterface.Mid0214 mid = new OpenProtocolInterpreter.IOInterface.Mid0214(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0215</para></remarks>
    public class TestMid0215 {
        public void runTests() {
            testRevision1();
            testRevision2();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0215 mid = new OpenProtocolInterpreter.IOInterface.Mid0215(-1, 1);
        }
        void testRevision2() {
            OpenProtocolInterpreter.IOInterface.Mid0215 mid = new OpenProtocolInterpreter.IOInterface.Mid0215(-1, 2);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0216</para></remarks>
    public class TestMid0216 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0216 mid = new OpenProtocolInterpreter.IOInterface.Mid0216(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0217</para></remarks>
    public class TestMid0217 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0217 mid = new OpenProtocolInterpreter.IOInterface.Mid0217(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0218</para></remarks>
    public class TestMid0218 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0218 mid = new OpenProtocolInterpreter.IOInterface.Mid0218(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0219</para></remarks>
    public class TestMid0219 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0219 mid = new OpenProtocolInterpreter.IOInterface.Mid0219(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0220</para></remarks>
    public class TestMid0220 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0220 mid = new OpenProtocolInterpreter.IOInterface.Mid0220(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0221</para></remarks>
    public class TestMid0221 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0221 mid = new OpenProtocolInterpreter.IOInterface.Mid0221(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0222</para></remarks>
    public class TestMid0222 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0222 mid = new OpenProtocolInterpreter.IOInterface.Mid0222(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0223</para></remarks>
    public class TestMid0223 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0223 mid = new OpenProtocolInterpreter.IOInterface.Mid0223(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0224</para></remarks>
    public class TestMid0224 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0224 mid = new OpenProtocolInterpreter.IOInterface.Mid0224(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.IOInterface.Mid0225</para></remarks>
    public class TestMid0225 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.IOInterface.Mid0225 mid = new OpenProtocolInterpreter.IOInterface.Mid0225(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PLCUserData.Mid0240</para></remarks>
    public class TestMid0240 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PLCUserData.Mid0240 mid = new OpenProtocolInterpreter.PLCUserData.Mid0240(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PLCUserData.Mid0241</para></remarks>
    public class TestMid0241 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PLCUserData.Mid0241 mid = new OpenProtocolInterpreter.PLCUserData.Mid0241(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PLCUserData.Mid0242</para></remarks>
    public class TestMid0242 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PLCUserData.Mid0242 mid = new OpenProtocolInterpreter.PLCUserData.Mid0242(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PLCUserData.Mid0243</para></remarks>
    public class TestMid0243 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PLCUserData.Mid0243 mid = new OpenProtocolInterpreter.PLCUserData.Mid0243(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PLCUserData.Mid0244</para></remarks>
    public class TestMid0244 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PLCUserData.Mid0244 mid = new OpenProtocolInterpreter.PLCUserData.Mid0244(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.PLCUserData.Mid0245</para></remarks>
    public class TestMid0245 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.PLCUserData.Mid0245 mid = new OpenProtocolInterpreter.PLCUserData.Mid0245(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationSelector.Mid0250</para></remarks>
    public class TestMid0250 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationSelector.Mid0250 mid = new OpenProtocolInterpreter.ApplicationSelector.Mid0250(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationSelector.Mid0251</para></remarks>
    public class TestMid0251 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationSelector.Mid0251 mid = new OpenProtocolInterpreter.ApplicationSelector.Mid0251(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationSelector.Mid0252</para></remarks>
    public class TestMid0252 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationSelector.Mid0252 mid = new OpenProtocolInterpreter.ApplicationSelector.Mid0252(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationSelector.Mid0253</para></remarks>
    public class TestMid0253 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationSelector.Mid0253 mid = new OpenProtocolInterpreter.ApplicationSelector.Mid0253(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationSelector.Mid0254</para></remarks>
    public class TestMid0254 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationSelector.Mid0254 mid = new OpenProtocolInterpreter.ApplicationSelector.Mid0254(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationSelector.Mid0255</para></remarks>
    public class TestMid0255 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationSelector.Mid0255 mid = new OpenProtocolInterpreter.ApplicationSelector.Mid0255(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0260</para></remarks>
    public class TestMid0260 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0260 mid = new OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0260(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0261</para></remarks>
    public class TestMid0261 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0261 mid = new OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0261(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0262</para></remarks>
    public class TestMid0262 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0262 mid = new OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0262(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0263</para></remarks>
    public class TestMid0263 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0263 mid = new OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0263(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0264</para></remarks>
    public class TestMid0264 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0264 mid = new OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0264(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0265</para></remarks>
    public class TestMid0265 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0265 mid = new OpenProtocolInterpreter.ApplicationToolLocationSystem.Mid0265(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ApplicationController.Mid0270</para></remarks>
    public class TestMid0270 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ApplicationController.Mid0270 mid = new OpenProtocolInterpreter.ApplicationController.Mid0270(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Statistic.Mid0300</para></remarks>
    public class TestMid0300 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Statistic.Mid0300 mid = new OpenProtocolInterpreter.Statistic.Mid0300(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Statistic.Mid0301</para></remarks>
    public class TestMid0301 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Statistic.Mid0301 mid = new OpenProtocolInterpreter.Statistic.Mid0301(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.AutomaticManualMode.Mid0400</para></remarks>
    public class TestMid0400 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.AutomaticManualMode.Mid0400 mid = new OpenProtocolInterpreter.AutomaticManualMode.Mid0400(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.AutomaticManualMode.Mid0401</para></remarks>
    public class TestMid0401 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.AutomaticManualMode.Mid0401 mid = new OpenProtocolInterpreter.AutomaticManualMode.Mid0401(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.AutomaticManualMode.Mid0402</para></remarks>
    public class TestMid0402 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.AutomaticManualMode.Mid0402 mid = new OpenProtocolInterpreter.AutomaticManualMode.Mid0402(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.AutomaticManualMode.Mid0403</para></remarks>
    public class TestMid0403 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.AutomaticManualMode.Mid0403 mid = new OpenProtocolInterpreter.AutomaticManualMode.Mid0403(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.AutomaticManualMode.Mid0410</para></remarks>
    public class TestMid0410 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.AutomaticManualMode.Mid0410 mid = new OpenProtocolInterpreter.AutomaticManualMode.Mid0410(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.AutomaticManualMode.Mid0411</para></remarks>
    public class TestMid0411 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.AutomaticManualMode.Mid0411 mid = new OpenProtocolInterpreter.AutomaticManualMode.Mid0411(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0420</para></remarks>
    public class TestMid0420 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0420 mid = new OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0420(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0421</para></remarks>
    public class TestMid0421 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0421 mid = new OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0421(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0422</para></remarks>
    public class TestMid0422 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0422 mid = new OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0422(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0423</para></remarks>
    public class TestMid0423 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0423 mid = new OpenProtocolInterpreter.OpenProtocolCommandsDisabled.Mid0423(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MotorTuning.Mid0500</para></remarks>
    public class TestMid0500 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MotorTuning.Mid0500 mid = new OpenProtocolInterpreter.MotorTuning.Mid0500(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MotorTuning.Mid0501</para></remarks>
    public class TestMid0501 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MotorTuning.Mid0501 mid = new OpenProtocolInterpreter.MotorTuning.Mid0501(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MotorTuning.Mid0502</para></remarks>
    public class TestMid0502 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MotorTuning.Mid0502 mid = new OpenProtocolInterpreter.MotorTuning.Mid0502(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MotorTuning.Mid0503</para></remarks>
    public class TestMid0503 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MotorTuning.Mid0503 mid = new OpenProtocolInterpreter.MotorTuning.Mid0503(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.MotorTuning.Mid0504</para></remarks>
    public class TestMid0504 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.MotorTuning.Mid0504 mid = new OpenProtocolInterpreter.MotorTuning.Mid0504(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Result.Mid1201</para></remarks>
    public class TestMid1201 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Result.Mid1201 mid = new OpenProtocolInterpreter.Result.Mid1201(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Result.Mid1202</para></remarks>
    public class TestMid1202 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Result.Mid1202 mid = new OpenProtocolInterpreter.Result.Mid1202(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.Result.Mid1203</para></remarks>
    public class TestMid1203 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.Result.Mid1203 mid = new OpenProtocolInterpreter.Result.Mid1203(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.ParameterSet.Mid2504</para></remarks>
    public class TestMid2504 {
        public void runTests() {
            testRevision1();
        }
        void testRevision1() {
            OpenProtocolInterpreter.ParameterSet.Mid2504 mid = new OpenProtocolInterpreter.ParameterSet.Mid2504(-1, 1);
        }
    }
    // <summary>test</summary>
    // <remarks><para>Type=OpenProtocolInterpreter.KeepAlive.Mid9999</para></remarks>
    public class TestMid9999 {
        public void runTests() {
            testRevision0();
        }
        void testRevision0() {
            OpenProtocolInterpreter.KeepAlive.Mid9999 mid = new OpenProtocolInterpreter.KeepAlive.Mid9999(-1, 0);
        }
    }
}
