//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Windows;
using System.Windows.Navigation;

namespace NSAtlasCopcoBreech {

	public partial class App : Application {
		MainWindow _mw;

		protected override void OnLoadCompleted(NavigationEventArgs e) {
			Utility.logger.log(MethodBase.GetCurrentMethod());
			base.OnLoadCompleted(e);
		}

		protected override void OnSessionEnding(SessionEndingCancelEventArgs e) {
			Utility.logger.log(MethodBase.GetCurrentMethod());
			base.OnSessionEnding(e);
		}

		void Application_Startup(object sender, StartupEventArgs e) {
			Utility.logger.log(MethodBase.GetCurrentMethod());
			_mw = new MainWindow();
			Application.Current.MainWindow = _mw;
			_mw.Show();
		}

		void Application_Exit(object sender, ExitEventArgs e) {
			Utility.logger.log(MethodBase.GetCurrentMethod());
			Utility.shutdown();
		}

		void Application_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e) {
			Utility.logger.log(MethodBase.GetCurrentMethod(), e.Exception);
			e.Handled = true;
		}
	}
}