//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;


namespace NSNewDriver {
    
    public partial class MainWindow : Window {
        MainWindowViewModel _vm;
        public MainWindow() {
            this.DataContext = (_vm = new MainWindowViewModel());
            InitializeComponent();
        }

		const string FRAME_KEY = "Main Window Frame";

		void Window1_Initialized(object sender, EventArgs e) {
			double left, top, width, height;

			if (Utility.retrieveWindowBounds(FRAME_KEY, out left, out top, out width, out height)) {
				//System.Diagnostics.Trace.WriteLine("Here");
				_vm.windowTop = top;
				_vm.windowLeft = left;
				_vm.windowWidth = width;
				_vm.windowHeight = height;
			} else {
				_vm.windowWidth = 325;
				_vm.windowHeight = 225;
				_vm.windowLeft = (SystemParameters.PrimaryScreenWidth - _vm.windowWidth) / 2.0;
				_vm.windowTop = (SystemParameters.PrimaryScreenHeight - _vm.windowHeight) / 2.0;
			}
			_vm.createListener("192.168.105.8", 4545);
		}

		void Window1_SizeChanged(object sender, SizeChangedEventArgs e) {
			Utility.saveWindowBoundsToRegistry(this, FRAME_KEY);
		}

		void Window1_LocationChanged(object sender, EventArgs e) {
			Utility.saveWindowBoundsToRegistry(this, FRAME_KEY);
		}

	}
}
